### ISSUE TITLE
question: seo

### ISSUE THREAD

**Issue by marcobiedermann** [erichs/awesome-awesome#10]
I've created a helpful list of search engine optimization tipps and tricks but it is not named with *awesome-* prefix. Is it okay, to add it or do you only wanna include repos which follow the naming convention?

https://github.com/marcobiedermann/search-engine-optimization

**Comment by erichs** [comment]
Hi! That list looks great. I'd like to keep this repo limited to lists with an awesome- prefix. Thanks for asking!

**Comment by marcobiedermann** [comment]
Alright, however you like to. I close it for now, but if you later decide to include it, hit me up :)
